#!/bin/sh

set -eu

MAP="/etc/owrt-installer/interface-map"

[ -f "$MAP" ] || exit 0

# shellcheck disable=SC1090 # The installer writes this trusted local file.
. "$MAP"

lower() {
	printf '%s' "$1" | tr 'A-F' 'a-f'
}

find_dev_by_mac() {
	wanted="$(lower "$1")"

	for devpath in /sys/class/net/*; do
		[ -e "$devpath" ] || continue
		name="$(basename "$devpath")"

		case "$name" in
			lo|br-*|docker*|veth*|tun*|tap*|wg*|ppp*|ifb*|gre*|erspan*|ip6tnl*|sit*)
				continue
				;;
		esac

		[ -f "$devpath/address" ] || continue
		mac="$(lower "$(cat "$devpath/address" 2>/dev/null)")"

		if [ "$mac" = "$wanted" ]; then
			printf '%s\n' "$name"
			return 0
		fi
	done

	return 1
}

LAN_DEV="$(find_dev_by_mac "$LAN_MAC" || true)"
WAN_DEV="$(find_dev_by_mac "$WAN_MAC" || true)"

if [ -z "$LAN_DEV" ] || [ -z "$WAN_DEV" ]; then
	logger -t owrt-installer "Could not map LAN/WAN MACs to device names"
	exit 1
fi

if [ "$LAN_DEV" = "$WAN_DEV" ]; then
	logger -t owrt-installer "LAN and WAN resolved to the same device, aborting"
	exit 1
fi

logger -t owrt-installer "Mapping complete: LAN=$LAN_DEV WAN=$WAN_DEV"

LAN_IP="${LAN_IP:-192.168.1.1}"
LAN_NETMASK="${LAN_NETMASK:-255.255.255.0}"
WAN_PROTO="${WAN_PROTO:-dhcp}"
WAN6_PROTO="${WAN6_PROTO:-dhcpv6}"

uci -q delete network.lan || true
uci -q delete network.wan || true
uci -q delete network.wan6 || true
uci -q delete network.br_lan || true

uci -q set network.br_lan=device
uci -q set network.br_lan.name='br-lan'
uci -q set network.br_lan.type='bridge'
uci -q add_list network.br_lan.ports="$LAN_DEV"

uci -q set network.lan=interface
uci -q set network.lan.device='br-lan'
uci -q set network.lan.proto='static'
uci -q set network.lan.ipaddr="$LAN_IP"
uci -q set network.lan.netmask="$LAN_NETMASK"

if [ "$WAN_PROTO" != "disabled" ]; then
	uci -q set network.wan=interface
	uci -q set network.wan.device="$WAN_DEV"
	uci -q set network.wan.proto="$WAN_PROTO"

	case "$WAN_PROTO" in
		pppoe)
			uci -q set network.wan.username="${WAN_PPP_USERNAME:-}"
			uci -q set network.wan.password="${WAN_PPP_PASSWORD:-}"
			uci -q set network.wan.ipv6='auto'
			;;
		static)
			uci -q set network.wan.ipaddr="${WAN_IPADDR:-}"
			uci -q set network.wan.netmask="${WAN_NETMASK:-255.255.255.0}"
			[ -n "${WAN_GATEWAY:-}" ] && uci -q set network.wan.gateway="$WAN_GATEWAY"
			for dns in ${WAN_DNS:-}; do
				uci -q add_list network.wan.dns="$dns"
			done
			;;
	esac

	if [ "$WAN6_PROTO" != "disabled" ]; then
		uci -q set network.wan6=interface
		if [ "$WAN_PROTO" = "pppoe" ]; then
			uci -q set network.wan6.device='@wan'
		else
			uci -q set network.wan6.device="$WAN_DEV"
		fi
		uci -q set network.wan6.proto="$WAN6_PROTO"
	fi
fi

uci -q commit network

uci -q batch <<EOF_UCI_DHCP
delete dhcp.lan
delete dhcp.wan

set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'

set dhcp.wan=dhcp
set dhcp.wan.interface='wan'
set dhcp.wan.ignore='1'

commit dhcp
EOF_UCI_DHCP

while uci -q delete 'firewall.@forwarding[0]'; do :; done
while uci -q delete 'firewall.@zone[0]'; do :; done

uci -q add firewall zone
uci -q set firewall.@zone[-1].name='lan'
uci -q set firewall.@zone[-1].input='ACCEPT'
uci -q set firewall.@zone[-1].output='ACCEPT'
uci -q set firewall.@zone[-1].forward='ACCEPT'
uci -q add_list firewall.@zone[-1].network='lan'

if [ "$WAN_PROTO" != "disabled" ]; then
	uci -q add firewall zone
	uci -q set firewall.@zone[-1].name='wan'
	uci -q set firewall.@zone[-1].input='REJECT'
	uci -q set firewall.@zone[-1].output='ACCEPT'
	uci -q set firewall.@zone[-1].forward='REJECT'
	uci -q set firewall.@zone[-1].masq='1'
	uci -q set firewall.@zone[-1].mtu_fix='1'
	uci -q add_list firewall.@zone[-1].network='wan'
	[ "$WAN6_PROTO" != "disabled" ] && uci -q add_list firewall.@zone[-1].network='wan6'

	uci -q add firewall forwarding
	uci -q set firewall.@forwarding[-1].src='lan'
	uci -q set firewall.@forwarding[-1].dest='wan'
fi

uci -q commit firewall

logger -t owrt-installer "Configured router: br-lan=$LAN_DEV, wan=$WAN_DEV proto=$WAN_PROTO"

exit 0
